# config.yaml
#   Base Configuration for Mjolnir. Add arguments to populate, but working suggestion is to build separate
#   sub-directories to shard configuration over datasets, preprocessing, models, etc. Inheritance and core paths can
#   all be overridden from the command line or by re-writing/adding to these files.
---
# Should be a list corresponding to the sub-configurations you're importing from!
# inherit:
#     - datasets/<dataset>.yaml
#     - models/<model>.yaml

# Run ID -- defaults to `null`; override as you like!
run_id: null

# Random Seed
seed: 21
